import os
import shutil
import glob

# Paths
base_dir = r"C:\Users\NC\Music\trxt nullivance v14"
target_dir = os.path.join(base_dir, r"paper\TRXT_V7_Release\source_code")

print(f"Target Repository: {target_dir}")

# Define new structure
new_dirs = [
    "data/raw",
    "data/sparc",
    "data/cmb",
    "data/bullet_cluster",
    "src/phase_v11_npl_fixes",
    "src/phase_v12_pure_geometry",
    "src/phase_j_expert_audit_recovery",
    "src/simulations_and_validations",
    "results/figures",
    "results/logs",
    "docs"
]

# 1. Safely clean root of target_dir
print("\n--- Cleaning old flat structure ---")
for item in os.listdir(target_dir):
    item_path = os.path.join(target_dir, item)
    if os.path.isfile(item_path):
        if item.endswith(".py") or item.endswith(".txt") or item.endswith(".png"):
            print(f"Removing old flat file: {item}")
            os.remove(item_path)
    elif os.path.isdir(item_path) and item not in ["data", "src", "results", "docs", "tests", "bbn_prymordial"]:
        print(f"Removing old directory: {item}")
        shutil.rmtree(item_path)

# 2. Create new structure
print("\n--- Creating standard GitHub structure ---")
for d in new_dirs:
    p = os.path.join(target_dir, d)
    os.makedirs(p, exist_ok=True)

# 3. Categorize and copy files from base_dir to target_dir
print("\n--- Migrating Source Code & Resolving Phase Dependencies ---")

def copy_files(pattern, dest_folder, move=False):
    files = glob.glob(os.path.join(base_dir, pattern))
    dest = os.path.join(target_dir, dest_folder)
    for f in files:
        if os.path.isfile(f):
            if move:
                shutil.move(f, os.path.join(dest, os.path.basename(f)))
            else:
                shutil.copy2(f, dest)
            print(f"{'Moved' if move else 'Copied'}: {os.path.basename(f)} -> {dest_folder}")

# V11 additions
copy_files("v11_*.py", r"src\phase_v11_npl_fixes")

# V12 pure geometry
copy_files("v12_*.py", r"src\phase_v12_pure_geometry")
copy_files("derive_*.py", r"src\phase_v12_pure_geometry")
copy_files("test_topological*.py", r"src\phase_v12_pure_geometry")
copy_files("topological_crystallization.png", r"results\figures")

# Phase J
copy_files("v14_j*.py", r"src\phase_j_expert_audit_recovery")
copy_files("v14_j*.txt", r"results\logs")

# Simulations (NPL gates and Bullet cluster)
copy_files("npl_*.py", r"src\simulations_and_validations")
copy_files("bullet_cluster*.py", r"src\simulations_and_validations")
copy_files("baryogenesis*.py", r"src\simulations_and_validations")
copy_files("lt_*.py", r"src\simulations_and_validations")

# Figures generated by simulations
copy_files("bullet_*.png", r"results\figures")
copy_files("defect_census_*.png", r"results\figures")
copy_files("npl_*.png", r"results\figures")
copy_files("baryogenesis*.png", r"results\figures")
copy_files("layer0*.png", r"results\figures")
copy_files("lt_*.png", r"results\figures")

# 4. Moving Experimental Data
print("\n--- Migrating Experimental Data to /data ---")
# Copy everything from base_dir/data to target_dir/data
src_data = os.path.join(base_dir, "data")
if os.path.exists(src_data):
    for item in os.listdir(src_data):
        s = os.path.join(src_data, item)
        d = os.path.join(target_dir, "data", item)
        if os.path.isdir(s):
            if not os.path.exists(d):
                shutil.copytree(s, d)
        elif os.path.isfile(s):
            shutil.copy2(s, d)
    print("Copied all standard datasets from /data.")

# Also move bullet fits
copy_files("bullet_*.fits", r"data\bullet_cluster", move=True)
copy_files("bullet_*out.txt", r"results\logs")

# Create README.md
readme_path = os.path.join(target_dir, "README.md")
with open(readme_path, "w", encoding='utf-8') as f:
    f.write("""# TRXT-NULLIVANCE: Source Code Repository (V14 Release)

This repository contains the complete, reproducible source code and experimental datasets for the TRXT "Truth via Emergence" Research Program.

## Scientific Structure

*   **/data**: Observational datasets (Planck 2018, SPARC rotation curves, Bullet Cluster Chandra X-Ray / Lensing mass maps, PDG 2024 parameters).
*   **/src/phase_v11_npl_fixes**: The initial non-perturbative logic transition (Entropic to Acoustic metric).
*   **/src/phase_v12_pure_geometry**: Rigorous topological derivation of the Standard Model (Koide 2/3 phase, Weak Chirality, Knot Mass Gaps).
*   **/src/simulations_and_validations**: Global PDE solvers for the 5 Gates (Bullet Cluster 2D separation, SPARC PDE, Solar Vainshtein 3D).
*   **/src/phase_j_expert_audit_recovery**: The 9 mathematical breakthrough scripts derived dynamically to conquer the independent expert peer review anomalies.
*   **/results**: Generated figures and physics resolution logs.

## Execution Principle (Master Protocol V2)
All scripts operate under the **"Anti-Hardcode Law"**. The framework parameters ($M^*, n, \beta, \Omega_\Lambda$) are **never** manually tuned to fit data. They emerge dynamically from the underlying topological logic tensor network.
""")

print("\nDONE: Repository reorganized successfully. Please review C:\\Users\\NC\\Music\\trxt nullivance v14\\paper\\TRXT_V7_Release\\source_code")
